#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/racecar.h"
#include "images/title.h"
#include "images/gameover.h"
#include "images/tire.h"


/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  PLAY,
  WIN,
  LOSE,
} GBAState;

// typedef struct Car {
//   int row;
//   int col;
// } Car;

// typedef struct Roadblock {
//   int row;
//   int col;
//   int drow;
//   int dcol;
// } Roadblock;

#define NUMTIRES 5

char scoreBuffer[8];


int play(void) {
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  fillScreenDMA(BLACK);

  Tire tires[NUMTIRES];
  Tire oldTires[NUMTIRES];
  Tire *cur;
  int deltas[] = {-3, -2, -1, 1, 2, 3};
  int numdeltas = sizeof(deltas) / sizeof(deltas[0]);

  for (int i = 0; i < NUMTIRES; i++) {
    tires[i].row = rand()%50 + 12;
    tires[i].col = rand()%50 + 12;
    tires[i].drow = deltas[rand()%numdeltas];
    tires[i].dcol = deltas[rand()%numdeltas];
    oldTires[i] = tires[i];
  } 

  fillScreenDMA(BLACK);

  Car car = {20, 120};
  Car oldCar = car;

  int score = 0;

  drawString(0, 190, "Score:", WHITE);
  drawChar(8, 190, '0', WHITE);
  drawCar(car.row, car.col);
  for (int i = 0; i < NUMTIRES; i++) {
    drawTire(tires[i].row, tires[i].col);
    oldTires[i] = tires[i];
  }

  drawChar(76, 117, '3', WHITE);
  for (int i = 0; i < 500; i++) {
    waitForVBlank();
  }

  drawRectDMA(76, 117, 6, 8, BLACK);
  drawChar(76, 117, '2', WHITE);
  for (int i = 0; i < 500; i++) {
    waitForVBlank();
  }

  drawRectDMA(76, 117, 6, 8, BLACK);
  drawChar(76, 117, '1', WHITE);
  for (int i = 0; i < 500; i++) {
    waitForVBlank();
  }

  drawRectDMA(76, 117, 6, 8, BLACK);

  while(1) {
    if(KEY_DOWN(BUTTON_UP, BUTTONS)) {
      car.row -= 2;
      if (car.row < 2) {
        car.row = 2;
      }
    }
    if(KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
      car.row += 2;
      if (car.row > 136) {
        car.row = 136;
      }
    }
    if(KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
      car.col -= 2;
      if (car.col < 2) {
        car.col = 2;
      }
    }
    if(KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
      car.col += 2;
      if (car.col > 183) {
        car.col = 183;
      }
    }
    if(KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
      return START;
    }

    for (int i = 0; i < NUMTIRES; i++) {
      cur = tires + i;
      cur->row = cur->row + cur->drow;
      cur->col = cur->col + cur->dcol;

      if(cur->row < 2) {
        cur->row = 2;
        cur->drow = -cur->drow;
      }
      if(cur->row > 153) {
        cur->row = 153;
        cur->drow = -cur->drow;
      }
      if(cur->col < 2) {
        cur->col = 2;
        cur->dcol = -cur->dcol;
      }
      if(cur->col > 183) {
        cur->col = 183;
        cur->dcol = -cur->dcol;
      }

      if (collision(cur->col, cur->row, car.col, car.row)) {
        if (score < 1000) {
          return LOSE;
        } else {
          return WIN;
        }
      }
    }

    score++;
    if (score > 9999999) {
      return WIN;
    }

    sprintf(scoreBuffer, "%i", score);
    for (int i = 0; i < 10; i++) {
      waitForVBlank();
    }
    // waitForVBlank();
    drawRectDMA(8, 190, 42, 8, BLACK);
    drawString(8, 190, scoreBuffer, WHITE);

    drawRectDMA(oldCar.row, oldCar.col, RACECAR_WIDTH, RACECAR_HEIGHT, BLACK);
    oldCar = car;

    // for (int i = 0; i < 500; i++) {
    // waitForVBlank();
    // }

    drawCar(car.row, car.col);

    for (int i = 0; i < NUMTIRES; i++) {
      drawRectDMA(oldTires[i].row, oldTires[i].col, TIRE_WIDTH, TIRE_HEIGHT, BLACK);
    }

    for (int i = 0; i < NUMTIRES; i++) {
      drawTire(tires[i].row, tires[i].col);
      oldTires[i] = tires[i];
    }

  }

}


void start(void) {
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  drawFullScreenImageDMA(title);
  drawString(10, 60, "Press ENTER To PLAY", WHITE);
  drawString(20, 10, "REACH A SCORE OF 1000 or more TO WIN", WHITE);
  drawString(140, 45, "Press BACKSPACE to Restart", WHITE);

  while(!KEY_DOWN(BUTTON_START, BUTTONS));
  while(KEY_DOWN(BUTTON_START, BUTTONS));
}

void lose(void) {

  drawFullScreenImageDMA(gameover);

  drawString(132, 45, "Press ENTER to Play Again", WHITE);

  while(!KEY_DOWN(BUTTON_START, BUTTONS));
  while(KEY_DOWN(BUTTON_START, BUTTONS));
}

void win(void) {

  fillScreenDMA(BLACK);

  drawString(20, 85, "YOU WIN! :)", WHITE);
  drawString(70, 98, "Score:", WHITE);
  drawString(80, 104, scoreBuffer, WHITE);

  drawString(132, 45, "Press Start to Play Again", WHITE);

  while(!KEY_DOWN(BUTTON_START, BUTTONS));
  while(KEY_DOWN(BUTTON_START, BUTTONS));
}

int main(void) {
  int state = START;
  while(1) {
    switch(state) {
      case START:
        start();
        state = PLAY;
        break;
      case PLAY:
        state = play();
        break;
      case LOSE:
        lose();
        state = START;
        break;
      case WIN:
        win();
        state = START;
        break;
      default:
        break;
    }
  }
}

// int main(void) {
//   /* TODO: */
//   // Manipulate REG_DISPCNT here to set Mode 3. //

//   // Save current and previous state of button input.
//   u32 previousButtons = BUTTONS;
//   u32 currentButtons = BUTTONS;

//   // Load initial game state
//   GBAState state = START;

//   while (1) {
//     currentButtons = BUTTONS;  // Load the current state of the buttons

//     /* TODO: */
//     // Manipulate the state machine below as needed //
//     // NOTE: Call waitForVBlank() before you draw

//     switch (state) {
//       case START:

//         // state = ?
//         break;
//       case PLAY:

//         // state = ?
//         break;
//       case WIN:

//         // state = ?
//         break;
//       case LOSE:

//         // state = ?
//         break;
//     }

//     previousButtons = currentButtons;  // Store the current state of the buttons
//   }

//   UNUSED(previousButtons);  // You can remove this once previousButtons is used

//   return 0;
// }
